// src/pages/ExpensesPage.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <Header />
    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Alert -->
      <div v-if="alert.message" :class="`p-4 mb-4 rounded-md ${alert.type === 'success' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`">
        {{ alert.message }}
      </div>

      <!-- Header -->
      <div class="flex justify-between items-center mb-6">
        <h2 class="text-3xl font-bold text-gray-900">Expense Dashboard</h2>
        <div class="flex space-x-4">
          <button @click="openAddModal" class="btn btn-primary bg-primary hover:bg-primary/90">
            <Plus class="h-4 w-4 mr-2" /> Add New Expense
          </button>
          <button @click="exportData" class="btn btn-outline">
            <Download class="h-4 w-4 mr-2" /> Export Data
          </button>
        </div>
      </div>

      <!-- Summary Cards -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div class="bg-white p-6 rounded-lg shadow-sm border">
          <h3 class="text-lg font-semibold mb-2">Total Expenses</h3>
          <p class="text-2xl font-bold">${{ overallTotal.toFixed(2) }}</p>
          <p class="text-sm text-gray-500">{{ entries.length }} entries</p>
        </div>
        <div class="bg-white p-6 rounded-lg shadow-sm border">
          <h3 class="text-lg font-semibold mb-2">Monthly Average</h3>
          <p class="text-2xl font-bold">$0.00</p>
          <p class="text-sm text-gray-500">Based on current filters</p>
        </div>
        <div class="bg-white p-6 rounded-lg shadow-sm border">
          <h3 class="text-lg font-semibold mb-2">Weekly Average</h3>
          <p class="text-2xl font-bold">$0.00</p>
          <p class="text-sm text-gray-500">Based on current filters</p>
        </div>
      </div>

      <!-- Filters Section -->
      <div class="bg-white p-6 rounded-lg shadow-sm border mb-8">
        <h3 class="text-lg font-semibold mb-4 flex items-center">
          <Filter class="h-5 w-5 mr-2" /> Advanced Filters
        </h3>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <div class="filter-group date-range-group">
            <label class="block text-sm font-medium text-gray-700 mb-2">Date Range</label>
            <div class="date-input-group flex items-center gap-2 p-2 bg-white border rounded-md min-h-[2.5rem]">
              <input 
                type="date" 
                v-model="currentFilters.startDate" 
                class="flex-1 border-0 outline-none"
                placeholder="Start Date"
              />
              <span class="date-separator text-gray-500">to</span>
              <input 
                type="date" 
                v-model="currentFilters.endDate" 
                class="flex-1 border-0 outline-none"
                placeholder="End Date"
              />
            </div>
          </div>

          <div class="filter-group">
            <label class="block text-sm font-medium text-gray-700 mb-2">Category</label>
            <select v-model="currentFilters.category" class="p-2 border rounded-md min-h-[2.5rem] w-full">
              <option value="">All Categories</option>
              <option v-for="cat in categories" :key="cat" :value="cat">{{ cat }}</option>
            </select>
          </div>

          <div class="filter-group">
            <label class="block text-sm font-medium text-gray-700 mb-2">Amount Range</label>
            <select v-model="currentFilters.amountRange" class="p-2 border rounded-md min-h-[2.5rem] w-full">
              <option value="">All Amounts</option>
              <option value="0-50">$0 - $50</option>
              <option value="50-100">$50 - $100</option>
              <option value="100-500">$100 - $500</option>
              <option value="500+">$500+</option>
            </select>
          </div>

          <div class="filter-group">
            <label class="block text-sm font-medium text-gray-700 mb-2">Search</label>
            <input 
              type="text" 
              v-model="currentFilters.search" 
              placeholder="Search by title or description"
              class="p-2 border rounded-md min-h-[2.5rem] w-full"
            />
          </div>
        </div>
        <div class="flex justify-end space-x-2 mt-6">
          <button @click="clearFilters" class="btn btn-outline">Clear Filters</button>
          <button @click="applyAdvancedFilters" class="btn btn-primary">Apply Filters</button>
        </div>
      </div>

      <!-- Expense List -->
      <div class="bg-white p-6 rounded-lg shadow-sm border">
        <div class="flex justify-between items-center mb-6">
          <h3 class="text-lg font-semibold">Expense List</h3>
          <div class="flex space-x-2">
            <button @click="toggleGrouping" class="btn btn-outline">
              <CalendarDays class="h-4 w-4 mr-2" /> Group by {{ currentGrouping === 'month' ? 'Week' : 'Month' }}
            </button>
            <button @click="toggleView" class="btn btn-outline">
              <LayoutGrid v-if="viewMode === 'table'" class="h-4 w-4 mr-2" />
              <List v-else class="h-4 w-4 mr-2" />
              {{ viewMode === 'table' ? 'Card View' : 'Table View' }}
            </button>
          </div>
        </div>

        <!-- Table View -->
        <ExpenseTable 
          v-if="viewMode === 'table'"
          :entries="entries"
          @edit="openEditModal"
          @delete="deleteEntry"
        />

        <!-- Card View (Grouped) -->
        <div v-else>
          <div v-if="Object.keys(grouped).length === 0" class="text-center text-gray-500 py-8">
            No expenses found for the selected filters.
          </div>

          <div v-else>
            <div v-for="groupKey in sortedGroupKeys" :key="groupKey" class="mb-8 last:mb-0">
              <h3 class="text-xl font-semibold text-gray-800 mb-4 flex justify-between items-center">
                {{ groupKey }}
                <span class="text-base font-medium text-gray-600">
                  Subtotal: ${{ totals[groupKey].subtotal.toFixed(2) }} ({{ totals[groupKey].count }} entries)
                </span>
              </h3>
              <div class="space-y-4">
                <div v-for="entry in grouped[groupKey]" :key="entry.id" class="flex items-center justify-between bg-white p-4 rounded-lg shadow-sm border">
                  <div class="flex-1">
                    <p class="text-lg font-medium text-gray-900">{{ entry.title }}</p>
                    <p class="text-sm text-gray-600">{{ entry.description }}</p>
                    <span class="inline-block mt-1 px-2 py-0.5 bg-blue-100 text-blue-800 text-xs font-medium rounded-full">
                      {{ entry.category }}
                    </span>
                    <p class="text-xs text-gray-500 mt-1">
                      {{ entry.expense_date ? `Expense Date: ${new Date(entry.expense_date).toLocaleDateString()}` : '' }} | Added: {{ new Date(entry.created_at).toLocaleDateString() }}
                    </p>
                  </div>
                  <div class="text-right">
                    <p class="text-xl font-bold text-primary">${{ entry.amount.toFixed(2) }}</p>
                    <div class="flex space-x-2 mt-2">
                      <button @click="openEditModal(entry)" class="btn btn-outline btn-sm">
                        <Edit class="h-4 w-4" />
                      </button>
                      <button @click="deleteEntry(entry.id)" class="btn btn-destructive btn-sm">
                        <Trash2 class="h-4 w-4" />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Add/Edit Expense Modal -->
      <div v-if="isModalOpen" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
        <div class="bg-white rounded-lg p-6 w-full max-w-2xl">
          <h3 class="text-lg font-semibold mb-4">{{ editingEntry ? 'Edit Expense' : 'Add New Expense' }}</h3>
          
          <form @submit.prevent="submitForm" class="space-y-4">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div class="space-y-2">
                <label class="block text-sm font-medium text-gray-700">Title</label>
                <input 
                  v-model="form.title" 
                  required 
                  class="w-full p-2 border rounded-md"
                />
              </div>
              <div class="space-y-2">
                <label class="block text-sm font-medium text-gray-700">Amount</label>
                <input 
                  v-model="form.amount" 
                  type="number" 
                  step="0.01" 
                  required 
                  class="w-full p-2 border rounded-md"
                />
              </div>
            </div>
            
            <div class="space-y-2">
              <label class="block text-sm font-medium text-gray-700">Description</label>
              <textarea 
                v-model="form.description" 
                class="w-full p-2 border rounded-md h-20"
              />
            </div>
            
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div class="space-y-2">
                <label class="block text-sm font-medium text-gray-700">Category</label>
                <select v-model="form.category" required class="w-full p-2 border rounded-md">
                  <option value="">Select a category</option>
                  <option v-for="cat in expenseCategories" :key="cat" :value="cat">{{ cat }}</option>
                </select>
              </div>
              <div class="space-y-2">
                <label class="block text-sm font-medium text-gray-700">Expense Date</label>
                <input 
                  v-model="form.expense_date" 
                  type="date" 
                  class="w-full p-2 border rounded-md"
                />
              </div>
            </div>

            <div class="space-y-2">
              <label class="block text-sm font-medium text-gray-700">Attachments</label>
              <div
                :class="`border-2 border-dashed rounded-md p-4 text-center cursor-pointer transition-colors ${dragOver ? 'border-primary bg-blue-50' : 'border-gray-300 bg-white'}`"
                @dragover.prevent="dragOver = true"
                @dragleave="dragOver = false"
                @drop.prevent="handleDrop"
                @click="$refs.fileInput.click()"
              >
                <Upload class="mx-auto h-8 w-8 text-gray-400 mb-2" />
                <p class="text-sm text-gray-600">Drag & drop files here, or click to select</p>
                <input
                  ref="fileInput"
                  type="file"
                  multiple
                  @change="handleFileChange"
                  class="hidden"
                />
              </div>
              <div class="mt-4 grid grid-cols-3 gap-2">
                <div v-for="(preview, index) in filePreviews" :key="index" class="relative group">
                  <img :src="preview" alt="File preview" class="w-full h-24 object-cover rounded-md border" />
                  <button
                    type="button"
                    @click="removeFile(index)"
                    class="absolute top-1 right-1 h-6 w-6 p-0 rounded-full bg-red-500 text-white opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    <X class="h-3 w-3" />
                  </button>
                </div>
              </div>
            </div>

            <div class="flex justify-end space-x-2 pt-4 border-t">
              <button type="button" @click="closeModal" class="btn btn-outline">Cancel</button>
              <button type="submit" class="btn btn-primary">Save Expense</button>
            </div>
          </form>
        </div>
      </div>
    </main>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import Header from '../components/Header.vue'
import Footer from '../components/Footer.vue'
import ExpenseTable from '../components/ExpenseTable.vue'
import { Plus, Upload, Search, Filter, Download, Trash2, Edit, CalendarDays, X, LayoutGrid, List } from 'lucide-vue-next'

interface ExpenseEntry {
  id: number
  title: string
  description: string
  category: string
  amount: number
  expense_date: string
  created_at: string
  updated_at: string
  files: { filename: string; original_name: string; file_type: string }[]
}

interface FilterState {
  category?: string
  amountRange?: string
  search?: string
  startDate?: string
  endDate?: string
}

const entries = ref<ExpenseEntry[]>([])
const categories = ref<string[]>([])
const expenseCategories = ref<string[]>([])
const currentFilters = ref<FilterState>({})
const isModalOpen = ref(false)
const editingEntry = ref<ExpenseEntry | null>(null)
const form = ref({
  title: '',
  description: '',
  category: '',
  amount: '',
  expense_date: '',
  files: [] as File[]
})
const filePreviews = ref<string[]>([])
const dragOver = ref(false)
const alert = ref<{ message: string; type: 'success' | 'error' | '' }>({ message: '', type: '' })
const currentGrouping = ref<'month' | 'week'>('month')
const viewMode = ref<'table' | 'cards'>('table')

const showAlert = (message: string, type: 'success' | 'error') => {
  alert.value = { message, type }
  setTimeout(() => alert.value = { message: '', type: '' }, 3000)
}

const loadEntries = async () => {
  const queryParams = new URLSearchParams()
  if (currentFilters.value.category) queryParams.append('category', currentFilters.value.category)
  if (currentFilters.value.amountRange) queryParams.append('amountRange', currentFilters.value.amountRange)
  if (currentFilters.value.search) queryParams.append('search', currentFilters.value.search)
  if (currentFilters.value.startDate) queryParams.append('startDate', currentFilters.value.startDate)
  if (currentFilters.value.endDate) queryParams.append('endDate', currentFilters.value.endDate)

  try {
    const response = await fetch(`/api/entries?${queryParams.toString()}`)
    if (!response.ok) throw new Error('Failed to fetch entries')
    const data = await response.json()
    entries.value = data
  } catch (error: any) {
    console.error('Error loading entries:', error)
    showAlert('Error loading entries: ' + error.message, 'error')
  }
}

const loadCategories = async () => {
  try {
    const response = await fetch('/api/categories')
    if (!response.ok) throw new Error('Failed to fetch categories')
    const data = await response.json()
    categories.value = data
  } catch (error: any) {
    console.error('Error loading categories:', error)
  }
}

const loadExpenseCategories = async () => {
  try {
    const response = await fetch('/api/expense-categories')
    if (!response.ok) throw new Error('Failed to fetch expense categories')
    const data = await response.json()
    expenseCategories.value = data
  } catch (error: any) {
    console.error('Error loading expense categories:', error)
  }
}

const applyAdvancedFilters = () => {
  loadEntries()
}

const clearFilters = () => {
  currentFilters.value = {}
  loadEntries()
}

const toggleGrouping = () => {
  currentGrouping.value = currentGrouping.value === 'month' ? 'week' : 'month'
}

const toggleView = () => {
  viewMode.value = viewMode.value === 'table' ? 'cards' : 'table'
}

const openAddModal = () => {
  editingEntry.value = null
  form.value = {
    title: '',
    description: '',
    category: '',
    amount: '',
    expense_date: '',
    files: []
  }
  filePreviews.value = []
  isModalOpen.value = true
}

const openEditModal = (entry: ExpenseEntry) => {
  editingEntry.value = entry
  form.value = {
    title: entry.title,
    description: entry.description,
    category: entry.category,
    amount: entry.amount.toString(),
    expense_date: entry.expense_date ? entry.expense_date.split(' ')[0] : '',
    files: []
  }
  filePreviews.value = entry.files.map(f => `/uploads/${f.filename}`)
  isModalOpen.value = true
}

const closeModal = () => {
  isModalOpen.value = false
  editingEntry.value = null
  form.value = {
    title: '',
    description: '',
    category: '',
    amount: '',
    expense_date: '',
    files: []
  }
  filePreviews.value = []
}

const handleFileChange = (e: Event) => {
  const target = e.target as HTMLInputElement
  if (target.files) {
    const newFiles = Array.from(target.files)
    form.value.files = [...form.value.files, ...newFiles]
    newFiles.forEach(file => {
      const reader = new FileReader()
      reader.onloadend = () => {
        filePreviews.value = [...filePreviews.value, reader.result as string]
      }
      reader.readAsDataURL(file)
    })
  }
}

const handleDrop = (e: DragEvent) => {
  dragOver.value = false
  if (e.dataTransfer?.files) {
    const newFiles = Array.from(e.dataTransfer.files)
    form.value.files = [...form.value.files, ...newFiles]
    newFiles.forEach(file => {
      const reader = new FileReader()
      reader.onloadend = () => {
        filePreviews.value = [...filePreviews.value, reader.result as string]
      }
      reader.readAsDataURL(file)
    })
  }
}

const removeFile = (index: number) => {
  form.value.files.splice(index, 1)
  filePreviews.value.splice(index, 1)
}

const submitForm = async () => {
  const formData = new FormData()
  formData.append('title', form.value.title)
  formData.append('description', form.value.description)
  formData.append('category', form.value.category)
  formData.append('amount', form.value.amount)
  formData.append('expense_date', form.value.expense_date)
  form.value.files.forEach((file) => {
    formData.append('files', file)
  })

  const url = editingEntry.value ? `/api/entries/${editingEntry.value.id}` : '/api/entries'
  const method = editingEntry.value ? 'PUT' : 'POST'

  try {
    const response = await fetch(url, {
      method,
      body: formData,
    })

    if (!response.ok) {
      const errorData = await response.json()
      throw new Error(errorData.error || 'Failed to save entry')
    }

    showAlert('Entry saved successfully!', 'success')
    closeModal()
    loadEntries()
  } catch (error: any) {
    console.error('Error saving entry:', error)
    showAlert('Error saving entry: ' + error.message, 'error')
  }
}

const deleteEntry = async (id: number) => {
  if (!window.confirm('Are you sure you want to delete this entry?')) return

  try {
    const response = await fetch(`/api/entries/${id}`, {
      method: 'DELETE',
    })

    if (!response.ok) {
      const errorData = await response.json()
      throw new Error(errorData.error || 'Failed to delete entry')
    }

    showAlert('Entry deleted successfully!', 'success')
    loadEntries()
  } catch (error: any) {
    console.error('Error deleting entry:', error)
    showAlert('Error deleting entry: ' + error.message, 'error')
  }
}

const exportData = async () => {
  try {
    const response = await fetch('/api/export')
    if (!response.ok) throw new Error('Failed to export data')
    const blob = await response.blob()
    const url = window.URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `expenses-${new Date().toISOString().split('T')[0]}.zip`
    document.body.appendChild(a)
    a.click()
    window.URL.revokeObjectURL(url)
    document.body.removeChild(a)
    showAlert('Data exported successfully!', 'success')
  } catch (error: any) {
    console.error('Error exporting data:', error)
    showAlert('Error exporting data: ' + error.message, 'error')
  }
}

const groupEntries = (entries: ExpenseEntry[]) => {
  const grouped: { [key: string]: ExpenseEntry[] } = {}
  entries.forEach(entry => {
    const date = new Date(entry.expense_date || entry.created_at)
    let key: string
    if (currentGrouping.value === 'month') {
      key = date.toLocaleString('en-US', { year: 'numeric', month: 'long' })
    } else { // week
      const startOfWeek = new Date(date)
      startOfWeek.setDate(date.getDate() - date.getDay()) // Sunday
      const endOfWeek = new Date(startOfWeek)
      endOfWeek.setDate(startOfWeek.getDate() + 6) // Saturday
      key = `${startOfWeek.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} - ${endOfWeek.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`
    }
    if (!grouped[key]) {
      grouped[key] = []
    }
    grouped[key].push(entry)
  })
  return grouped
}

const calculateTotals = (groupedEntries: { [key: string]: ExpenseEntry[] }) => {
  const totals: { [key: string]: { subtotal: number; count: number } } = {}
  for (const key in groupedEntries) {
    const subtotal = groupedEntries[key].reduce((sum, entry) => sum + entry.amount, 0)
    totals[key] = { subtotal, count: groupedEntries[key].length }
  }
  return totals
}

const grouped = computed(() => groupEntries(entries.value))
const totals = computed(() => calculateTotals(grouped.value))
const overallTotal = computed(() => entries.value.reduce((sum, entry) => sum + entry.amount, 0))
const sortedGroupKeys = computed(() => 
  Object.keys(grouped.value).sort((a, b) => 
    new Date(b.split(' - ')[0]).getTime() - new Date(a.split(' - ')[0]).getTime()
  )
)

onMounted(() => {
  loadEntries()
  loadCategories()
  loadExpenseCategories()
})

watch(currentFilters, () => {
  loadEntries()
}, { deep: true })
</script>

// src/pages/ExpensesPage.tsx
import { useState, useEffect } from 'react'
import { Button } from '../components/ui/button'
import { Input } from '../components/ui/input'
import { Label } from '../components/ui/label'
import { Textarea } from '../components/ui/textarea'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../components/ui/card'
import { Plus, Download, Search, Filter, Calendar, DollarSign, FileText, Trash2, Edit, Eye } from 'lucide-react'

interface Expense {
  id: number
  title: string
  description: string
  category: string
  amount: number
  expense_date: string
  created_at: string
  updated_at: string
  files: File[]
}

interface SummaryStats {
  totalAmount: number
  monthlyAmount: number
  weeklyAmount: number
  dailyAverage: number
}

export function ExpensesPage() {
  const [expenses, setExpenses] = useState<Expense[]>([])
  const [filteredExpenses, setFilteredExpenses] = useState<Expense[]>([])
  const [summaryStats, setSummaryStats] = useState<SummaryStats>({
    totalAmount: 0,
    monthlyAmount: 0,
    weeklyAmount: 0,
    dailyAverage: 0
  })
  const [isModalOpen, setIsModalOpen] = useState(false)
  const [editingExpense, setEditingExpense] = useState<Expense | null>(null)
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    category: '',
    amount: '',
    expense_date: '',
    files: [] as File[]
  })
  const [filters, setFilters] = useState({
    startDate: '',
    endDate: '',
    category: '',
    amountRange: '',
    search: ''
  })
  const [categories, setCategories] = useState<string[]>([])
  const [loading, setLoading] = useState(true)

  // Load expenses on component mount
  useEffect(() => {
    loadExpenses()
    loadCategories()
  }, [])

  // Apply filters whenever filters change
  useEffect(() => {
    applyFilters()
  }, [expenses, filters])

  const loadExpenses = async () => {
    try {
      setLoading(true)
      const response = await fetch('/api/entries')
      const data = await response.json()
      setExpenses(data)
      calculateSummaryStats(data)
    } catch (error) {
      console.error('Error loading expenses:', error)
    } finally {
      setLoading(false)
    }
  }

  const loadCategories = async () => {
    try {
      const response = await fetch('/api/categories')
      const data = await response.json()
      setCategories(data)
    } catch (error) {
      console.error('Error loading categories:', error)
    }
  }

  const calculateSummaryStats = (expenseData: Expense[]) => {
    const now = new Date()
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1)
    const startOfWeek = new Date(now)
    startOfWeek.setDate(now.getDate() - now.getDay())

    const totalAmount = expenseData.reduce((sum, expense) => sum + expense.amount, 0)
    const monthlyAmount = expenseData
      .filter(expense => new Date(expense.expense_date) >= startOfMonth)
      .reduce((sum, expense) => sum + expense.amount, 0)
    const weeklyAmount = expenseData
      .filter(expense => new Date(expense.expense_date) >= startOfWeek)
      .reduce((sum, expense) => sum + expense.amount, 0)
    const dailyAverage = totalAmount / Math.max(1, expenseData.length)

    setSummaryStats({
      totalAmount,
      monthlyAmount,
      weeklyAmount,
      dailyAverage
    })
  }

  const applyFilters = () => {
    let filtered = [...expenses]

    // Date range filter
    if (filters.startDate) {
      filtered = filtered.filter(expense => 
        new Date(expense.expense_date) >= new Date(filters.startDate)
      )
    }
    if (filters.endDate) {
      filtered = filtered.filter(expense => 
        new Date(expense.expense_date) <= new Date(filters.endDate)
      )
    }

    // Category filter
    if (filters.category) {
      filtered = filtered.filter(expense => expense.category === filters.category)
    }

    // Amount range filter
    if (filters.amountRange) {
      const [min, max] = filters.amountRange.split('-').map(Number)
      filtered = filtered.filter(expense => {
        if (max) {
          return expense.amount >= min && expense.amount <= max
        } else {
          return expense.amount >= min
        }
      })
    }

    // Search filter
    if (filters.search) {
      const searchLower = filters.search.toLowerCase()
      filtered = filtered.filter(expense => 
        expense.title.toLowerCase().includes(searchLower) ||
        expense.description.toLowerCase().includes(searchLower)
      )
    }

    setFilteredExpenses(filtered)
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    const formDataToSend = new FormData()
    formDataToSend.append('title', formData.title)
    formDataToSend.append('description', formData.description)
    formDataToSend.append('category', formData.category)
    formDataToSend.append('amount', formData.amount)
    formDataToSend.append('expense_date', formData.expense_date)
    
    formData.files.forEach(file => {
      formDataToSend.append('files', file)
    })

    try {
      const url = editingExpense ? `/api/entries/${editingExpense.id}` : '/api/entries'
      const method = editingExpense ? 'PUT' : 'POST'
      
      const response = await fetch(url, {
        method,
        body: formDataToSend
      })

      if (response.ok) {
        setIsModalOpen(false)
        setFormData({
          title: '',
          description: '',
          category: '',
          amount: '',
          expense_date: '',
          files: []
        })
        setEditingExpense(null)
        loadExpenses()
      }
    } catch (error) {
      console.error('Error saving expense:', error)
    }
  }

  const handleEdit = (expense: Expense) => {
    setEditingExpense(expense)
    setFormData({
      title: expense.title,
      description: expense.description,
      category: expense.category,
      amount: expense.amount.toString(),
      expense_date: expense.expense_date,
      files: []
    })
    setIsModalOpen(true)
  }

  const handleDelete = async (id: number) => {
    if (confirm('Are you sure you want to delete this expense?')) {
      try {
        const response = await fetch(`/api/entries/${id}`, {
          method: 'DELETE'
        })
        
        if (response.ok) {
          loadExpenses()
        }
      } catch (error) {
        console.error('Error deleting expense:', error)
      }
    }
  }

  const handleExport = async () => {
    try {
      const params = new URLSearchParams()
      if (filters.startDate) params.append('startDate', filters.startDate)
      if (filters.endDate) params.append('endDate', filters.endDate)
      if (filters.category) params.append('category', filters.category)

      const response = await fetch(`/api/export?${params}`)
      const blob = await response.blob()
      
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `expense_manager_export_${new Date().toISOString().split('T')[0]}.zip`
      document.body.appendChild(a)
      a.click()
      window.URL.revokeObjectURL(url)
      document.body.removeChild(a)
    } catch (error) {
      console.error('Error exporting data:', error)
    }
  }

  const clearFilters = () => {
    setFilters({
      startDate: '',
      endDate: '',
      category: '',
      amountRange: '',
      search: ''
    })
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="flex justify-between items-center mb-8">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Expense Management</h1>
            <p className="text-gray-600 mt-2">Track and manage your business expenses</p>
          </div>
          <div className="flex space-x-4">
            <Button onClick={() => setIsModalOpen(true)} className="bg-green-600 hover:bg-green-700">
              <Plus className="h-4 w-4 mr-2" />
              Add New Expense
            </Button>
            <Button variant="outline" onClick={handleExport}>
              <Download className="h-4 w-4 mr-2" />
              Export Data
            </Button>
          </div>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Total Amount</CardTitle>
              <DollarSign className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">${summaryStats.totalAmount.toFixed(2)}</div>
              <p className="text-xs text-muted-foreground">All time</p>
            </CardContent>
          </Card>
          
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">This Month</CardTitle>
              <Calendar className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">${summaryStats.monthlyAmount.toFixed(2)}</div>
              <p className="text-xs text-muted-foreground">Current month</p>
            </CardContent>
          </Card>
          
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">This Week</CardTitle>
              <Calendar className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">${summaryStats.weeklyAmount.toFixed(2)}</div>
              <p className="text-xs text-muted-foreground">Current week</p>
            </CardContent>
          </Card>
          
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Average Daily</CardTitle>
              <DollarSign className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">${summaryStats.dailyAverage.toFixed(2)}</div>
              <p className="text-xs text-muted-foreground">Per day</p>
            </CardContent>
          </Card>
        </div>

        {/* Filters */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="flex items-center">
              <Filter className="h-5 w-5 mr-2" />
              Advanced Filters
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="space-y-2">
                <Label htmlFor="startDate">Start Date</Label>
                <Input
                  id="startDate"
                  type="date"
                  value={filters.startDate}
                  onChange={(e) => setFilters({...filters, startDate: e.target.value})}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="endDate">End Date</Label>
                <Input
                  id="endDate"
                  type="date"
                  value={filters.endDate}
                  onChange={(e) => setFilters({...filters, endDate: e.target.value})}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="category">Category</Label>
                <select
                  id="category"
                  className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
                  value={filters.category}
                  onChange={(e) => setFilters({...filters, category: e.target.value})}
                >
                  <option value="">All Categories</option>
                  {categories.map(category => (
                    <option key={category} value={category}>{category}</option>
                  ))}
                </select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="search">Search</Label>
                <div className="relative">
                  <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                  <Input
                    id="search"
                    placeholder="Search expenses..."
                    className="pl-10"
                    value={filters.search}
                    onChange={(e) => setFilters({...filters, search: e.target.value})}
                  />
                </div>
              </div>
            </div>
            <div className="flex justify-end mt-4">
              <Button variant="outline" onClick={clearFilters}>
                Clear Filters
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Expense List */}
        <Card>
          <CardHeader>
            <CardTitle>Expense Details</CardTitle>
            <CardDescription>
              {filteredExpenses.length} expenses found
            </CardDescription>
          </CardHeader>
          <CardContent>
            {loading ? (
              <div className="flex items-center justify-center py-8">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
                <span className="ml-2">Loading expenses...</span>
              </div>
            ) : filteredExpenses.length === 0 ? (
              <div className="text-center py-8 text-muted-foreground">
                No expenses found. Add your first expense to get started.
              </div>
            ) : (
              <div className="space-y-4">
                {filteredExpenses.map((expense) => (
                  <div key={expense.id} className="flex items-center justify-between p-4 border rounded-lg hover:bg-gray-50">
                    <div className="flex items-center space-x-4">
                      <div className="w-10 h-10 bg-primary/10 rounded-full flex items-center justify-center">
                        <FileText className="h-5 w-5 text-primary" />
                      </div>
                      <div>
                        <h3 className="font-medium">{expense.title}</h3>
                        <p className="text-sm text-muted-foreground">{expense.category}</p>
                        <p className="text-xs text-muted-foreground">
                          {new Date(expense.expense_date).toLocaleDateString()}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center space-x-4">
                      <span className="font-semibold">${expense.amount.toFixed(2)}</span>
                      <div className="flex space-x-2">
                        <Button variant="ghost" size="sm" onClick={() => handleEdit(expense)}>
                          <Edit className="h-4 w-4" />
                        </Button>
                        <Button variant="ghost" size="sm" onClick={() => handleDelete(expense.id)}>
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Modal */}
        {isModalOpen && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
            <Card className="w-full max-w-2xl max-h-[90vh] overflow-y-auto">
              <CardHeader>
                <CardTitle>{editingExpense ? 'Edit Expense' : 'Add New Expense'}</CardTitle>
                <CardDescription>
                  {editingExpense ? 'Update expense details' : 'Fill in the expense details below'}
                </CardDescription>
              </CardHeader>
              <CardContent>
                <form onSubmit={handleSubmit} className="space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="title">Title *</Label>
                      <Input
                        id="title"
                        value={formData.title}
                        onChange={(e) => setFormData({...formData, title: e.target.value})}
                        required
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="amount">Amount *</Label>
                      <Input
                        id="amount"
                        type="number"
                        step="0.01"
                        min="0"
                        value={formData.amount}
                        onChange={(e) => setFormData({...formData, amount: e.target.value})}
                        required
                      />
                    </div>
                  </div>
                  
                  <div className="space-y-2">
                    <Label htmlFor="description">Description</Label>
                    <Textarea
                      id="description"
                      rows={3}
                      value={formData.description}
                      onChange={(e) => setFormData({...formData, description: e.target.value})}
                    />
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="category">Category *</Label>
                      <select
                        id="category"
                        className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
                        value={formData.category}
                        onChange={(e) => setFormData({...formData, category: e.target.value})}
                        required
                      >
                        <option value="">Select Category</option>
                        {categories.map(category => (
                          <option key={category} value={category}>{category}</option>
                        ))}
                      </select>
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="expense_date">Expense Date *</Label>
                      <Input
                        id="expense_date"
                        type="date"
                        value={formData.expense_date}
                        onChange={(e) => setFormData({...formData, expense_date: e.target.value})}
                        required
                      />
                    </div>
                  </div>
                  
                  <div className="space-y-2">
                    <Label htmlFor="files">Receipt Files</Label>
                    <Input
                      id="files"
                      type="file"
                      multiple
                      accept="image/*,.pdf"
                      onChange={(e) => {
                        const files = Array.from(e.target.files || [])
                        setFormData({...formData, files})
                      }}
                    />
                  </div>
                  
                  <div className="flex justify-end space-x-4 pt-4">
                    <Button type="button" variant="outline" onClick={() => setIsModalOpen(false)}>
                      Cancel
                    </Button>
                    <Button type="submit">
                      {editingExpense ? 'Update Expense' : 'Save Expense'}
                    </Button>
                  </div>
                </form>
              </CardContent>
            </Card>
          </div>
        )}
      </div>
    </div>
  )
}
